name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          token: ${{ secrets.THREE_JS_GITHUB_ACTION_PULL }} # Use the PAT instead of GITHUB_TOKEN
          pr_title: "Automated Pull Request for New Branch"
          pr_body: "A new branch has been pushed and this pull request has been created automatically."
          source_branch: ${{ github.ref_name }} # Adjusted input
          destination_branch: "main" # Adjusted input
