name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Automated Pull Request for New Branch"
        pr_body: "A new branch has been pushed and this pull request has been created automatically."
        pr_branch: ${{ github.ref }}
