name: Create and Merge Pull Request and Delete Branch

on:
  push:
    branches-ignore:
      - main

jobs:
  createPullRequest:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Check out code
        uses: actions/checkout@v4

      # Extract the name of the last commit in the branch
      - name: Get Last Commit Name
        id: last_commit
        run: |
          COMMIT_NAME=$(git log -1 --pretty=%B)
          echo "commit_name=$COMMIT_NAME" >> $GITHUB_ENV

      - name: create pull request
        run: gh pr create -B main -H dev --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          token: ${{ secrets.Act_Local_GitWorkFlowTesting }}

      #- name: Create Pull Request Updated
      #  uses: peter-evans/create-pull-request@v5
      #  with:
      #    token: ${{ secrets.Act_Local_GitWorkFlowTesting }#} # Your PAT or you can use GITHUB_TOKEN
      #    title: ${{ steps.last_commit.outputs.commit_name }#}
      #    body: "A new branch has been pushed and this pull request has been created automatically."
      #    branch: "Dev" #${{ github.head_ref }#} # The branch to create for the pull request
      #    base: "main" # The branch you want to merge your changes into
      #    labels: "Automated PR" # You can add more labels separated by commas
      #    # reviewers: "user1, user2" # Optional: Add if you want to specify reviewers
      #    # team_reviewers: "team1, team2" # Optional: Add if you want to specify team reviewers
      #    draft: false

  autoMerge:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
    needs: createPullRequest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: ${{ secrets.Act_Local_GitWorkFlowTesting }}
        with:
          mergeMethod: squash
          commitMessage: "Merge pull request #${{ github.event.pull_request.number }}"
          #pullRequestLabels: "automerge"

  deleteBranch:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    needs: autoMerge
    runs-on: ubuntu-latest
    steps:
      - name: Delete Branch
        run: git push origin --delete ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.THREE_JS_GITHUB_ACTION_PULL }}
