name: Create PR, Merge, Delete

on:
  push:
    branches-ignore:
      - main

jobs:
  createPullRequest:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Check out code
        uses: actions/checkout@v4

      # Extract the name of the last commit in the branch
      # Sed is used to handle special characters
      # Sed is used to handle special characters
      - name: Get Last Commit Name
        id: last_commit
        run: |
          COMMIT_NAME=$(git log -1 --pretty=%B | sed 's/[^a-zA-Z0-9 ]/_/g')
          echo "commit_name=$COMMIT_NAME" >> $GITHUB_ENV
      # Set base branch as an environment variable and get the name of the head branch
      - run: |
          echo "BASE_BRANCH=dev" >> $GITHUB_ENV
          HEAD_BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_ENV
      - name: create pull request
        run: gh pr create -B $BASE_BRANCH -H $HEAD_BRANCH --title "${{ env.commit_name }}" --body 'A new branch has been pushed and this pull request has been created automatically.'
        env:
          GH_TOKEN: ${{ secrets.ThreeJsWorkflowPat }}

  autoMerge:
    needs: createPullRequest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Get Last Commit Message
        run: |
          echo "LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Auto Merge
        run: |
          gh auth setup-git
          PR_NUMBER=$(gh pr view --json number --jq '.number')
          COMMIT_TITLE="Merge pull request: $PR_NUMBER"
          COMMIT_BODY="$LAST_COMMIT_MESSAGE"
          gh pr merge $PR_NUMBER --auto --squash -t "$COMMIT_TITLE" -b "$COMMIT_BODY"
        env:
          GH_TOKEN: ${{ secrets.ThreeJsWorkflowPat }}

  deleteBranch:
    needs: autoMerge
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Debugging step to check the branch name
      - name: Debug Branch Name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Branch Name: $BRANCH_NAME"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      # Replace 'your_branch_name' with the name of the branch you want to delete
      # Assuming the branch is merged and you want to delete it from remote
      - name: Delete Branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git push origin --delete $BRANCH_NAME
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
